test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local: 
  service: Disk
  root: <%= Rails.root.join("storage") %>

google:
  service: GCS
  project: slowduck 
  credentials: <%= ENV['GOOGLE_APPLICATION_CREDENTIALS'].as_json %>
  bucket: slowduck19production

google_dev:
  service: GCS
  project: slowduck 
  credentials: <%= Rails.root.join("config/secrets/slowduck.json") %>
  bucket: slowduck19production

